### ISSUE TITLE
create page that will open on share

### ISSUE THREAD

**Issue by michaelnyu** [michaelnyu/to-platform#14]
Should look like this.

Will be opened when user clicks share on extension or share on our webpage.

![image](https://user-images.githubusercontent.com/14363982/69763056-d5188100-1120-11ea-9e39-13bb81371328.png)

route: /share

**Comment by katiecai** [comment]
i can take this!

**Comment by katiecai** [comment]
https://github.com/michaelnyu/to-platform/pull/29
